# Generated by Django 5.0.7 on 2024-08-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='biome_data',
        ),
        migrations.RemoveField(
            model_name='chunk',
            name='environment_data',
        ),
        migrations.RemoveField(
            model_name='chunk',
            name='y',
        ),
        migrations.RemoveField(
            model_name='world',
            name='height',
        ),
        migrations.AddField(
            model_name='chunk',
            name='background_data',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
