# Generated by Django 5.0.7 on 2024-08-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0002_remove_chunk_biome_data_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chunk',
            unique_together={('world', 'x')},
        ),
    ]
