# Generated by Django 5.0.7 on 2024-08-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0003_alter_chunk_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='vx',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='vy',
            field=models.FloatField(default=0),
        ),
    ]
