# Generated by Django 5.0.7 on 2024-08-19 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0004_player_vx_player_vy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='background_data',
        ),
    ]
