# Generated by Django 5.0.7 on 2024-08-23 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0005_remove_chunk_background_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chunk',
            name='terrain_data',
        ),
        migrations.AddField(
            model_name='chunk',
            name='layer_0',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='chunk',
            name='layer_1',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='chunk',
            name='layer_2',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='chunk',
            name='layer_3',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='chunk',
            name='layer_4',
            field=models.JSONField(default=list),
        ),
    ]
