# Generated by Django 5.0.7 on 2024-08-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_app', '0006_remove_chunk_terrain_data_chunk_layer_0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pivot_points',
            field=models.TextField(default='{}'),
        ),
    ]
